SELECT * FROM NFL_QB;
Select * from NFL_QBTD; 
select * from nfl_qb_attempts; 
SELECT * FROM NFL_WR;
SELECT * FROM NFL_RB;
SELECT * FROM NFL_RB_RUSHES;

SELECT *
FROM NFL_QBTD
LEFT JOIN NFL_WR_TD
ON NFL_QBTD.ID_YEAR = NFL_WR_TD.ID_YEAR
WHERE NFL_QBTD.TEAM LIKE '%NO%' ; 

SELECT *
FROM NFL_QBTD
JOIN NFL_WR_TD
ON NFL_QBTD.ID_YEAR = NFL_WR_TD.ID_YEAR
WHERE NFL_QBTD.TEAM LIKE '%GB%'


SELECT nfl_qb.name, NFL_QB.comp,
	nfl_qb_attempts.name, nfl_qb_attempts.comp
FROM NFL_QB
JOIN NFL_QB_ATTEMPTS 
ON NFL_QB.ID_YEAR = NFL_QB_ATTEMPTS.ID_YEAR; 

-- Cases for passing attempts.
 

SELECT ID_YEAR, NAME, YDS,
	CASE 
		WHEN YDS >= 1800 THEN 'OVER 1800 YRDS'
		WHEN YDS >= 1900 THEN 'OVER 1900 YARDS'
		ELSE ' UNDER 1800 YARDS'
		END AS YARDS 
FROM NFL_RB; 

-- Each player in odd number years 
SELECT NFL_QB.ID_YEAR, NFL_QB.NAME, NFL_QB.YDS, 
	NFL_RB.NAME, NFL_RB.YDS, 
	NFL_WR.NAME, NFL_WR.YDS
FROM NFL_QB
	JOIN NFL_RB
	ON NFL_QB.ID_YEAR = NFL_RB.ID_YEAR
	JOIN NFL_WR
	ON NFL_RB.ID_YEAR = NFL_WR.ID_YEAR
WHERE NFL_QB.ID_YEAR IN (2011, 2013, 2015, 2017, 2019, 2021); 
	
-- Each player in even number years 
SELECT NFL_QB.ID_YEAR, NFL_QB.NAME, NFL_QB.YDS, 
	NFL_RB.NAME, NFL_RB.YDS, 
	NFL_WR.NAME, NFL_WR.YDS
FROM NFL_QB
	JOIN NFL_RB
	ON NFL_QB.ID_YEAR = NFL_RB.ID_YEAR
	JOIN NFL_WR
	ON NFL_RB.ID_YEAR = NFL_WR.ID_YEAR
WHERE NFL_QB.ID_YEAR IN (2010, 2012, 2014, 2016, 2018, 2020, 2022); 



